CREATE DATABASE [CacheDB]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'CacheDB_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CacheDB.mdf', -- указать местоположение
	SIZE = 10GB , MAXSIZE = UNLIMITED, FILEGROWTH = 10% )
 LOG ON 
( NAME = N'CacheDB_Log', 
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CacheDB.ldf', -- указать местоположение
	SIZE = 2GB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO