CREATE NONCLUSTERED INDEX [IX_InvestorFundDate_FundId_Date] ON [dbo].[InvestorFundDate]
(
	[FundId] ASC,
	[Date] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_InvestorFundDate_ID]
ON [dbo].[InvestorFundDate] ([Investor],[Date])
GO
CREATE NONCLUSTERED INDEX [IX_InvestorFundDate_FundId_DateLast] ON [dbo].[InvestorFundDateLast]
(
	[FundId] ASC,
	[Date] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_InvestorFundDateLast_ID]
ON [dbo].[InvestorFundDateLast] ([Investor],[Date])
GO
CREATE NONCLUSTERED INDEX [IX_POSITION_KEEPING_Fifo_Date] ON [dbo].[POSITION_KEEPING]
(
	[InvestorId] ASC,
	[ContractId] ASC,
	[Fifo_Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [IX_POSITION_KEEPING_Fifo_Date_Last] ON [dbo].[POSITION_KEEPING_Last]
(
	[InvestorId] ASC,
	[ContractId] ASC,
	[Fifo_Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Operations_History_Contracts]
ON [dbo].[Operations_History_Contracts] ([InvestorId],[ContractId])
GO
CREATE NONCLUSTERED INDEX [IX_Operations_History_Contracts_Last]
ON [dbo].[Operations_History_Contracts_Last] ([InvestorId],[ContractId])
GO






CREATE NONCLUSTERED INDEX [IX_TURNS_REST_WIRDATE_IS_PLAN] ON [dbo].[OD_TURNS]
(
	[REST] ASC,
	[WIRDATE] ASC,
	[IS_PLAN] ASC
)
INCLUDE([WIRING],[VALUE_])
GO
CREATE INDEX [IX_OD_VALUES_RATES_VOE] 
ON [dbo].[OD_VALUES_RATES] 
([VALUE_ID],[OFICDATE], [E_DATE]) INCLUDE ([RATE])
GO

CREATE INDEX [IX_OD_RESTS_REG_1]
ON [dbo].[OD_RESTS] ([REG_1])
GO

CREATE NONCLUSTERED INDEX [IX_VALUES_OFICDATE_E_DATE]
ON [dbo].[OD_VALUES_RATES] ([VALUE_ID],[OFICDATE],[E_DATE])
INCLUDE ([RATE])
GO

CREATE NONCLUSTERED INDEX [TMP_FIFO_JOURNAL_APPL_ID_OA] ON [dbo].[TMP_FIFO_JOURNAL]
(
	[APPL_ID] ASC,
	[OUT_WIR] ASC,
	[AMOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [TMP_FIFO_JOURNAL_APPL_ID_IO] ON [dbo].[TMP_FIFO_JOURNAL]
(
	[APPL_ID] ASC,
	[IN_WIR] ASC,
	[OUT_WIR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO