// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsProcatt.ModelDB
{
    public partial class CircleDiagramsResult
    {
        public int? ISPIF { get; set; }
        public int ContractId { get; set; }
        public string ContractName { get; set; }
        public string GroupType { get; set; }
        public string CategoryName { get; set; }
        public decimal? VALUE_CUR { get; set; }
        public decimal? Res { get; set; }
    }
}
