// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsProcatt.ModelDB
{
    public partial class ContractsDataResult
    {
        public int InvestorId { get; set; }
        public int ContractId { get; set; }
        public DateTime Date { get; set; }
        public decimal? VALUE { get; set; }
        public decimal? INPUT_VALUE { get; set; }
        public decimal? OUTPUT_VALUE { get; set; }
        public decimal? INPUT_DIVIDENTS { get; set; }
        public decimal? INPUT_COUPONS { get; set; }
        public bool? ISPIF { get; set; }
        public string LS_NUM { get; set; }
        public decimal? SumAmount { get; set; }
    }
}
