// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsProcatt.ModelDB
{
    public partial class ContractsDataSumResult
    {
        public int? ISPIF { get; set; }
        public int ContractId { get; set; }
        public string Name { get; set; }
        public string LS_NUM { get; set; }
        public decimal? SumAmount { get; set; }
        public DateTime? DATE_OPEN { get; set; }
        public DateTime? DATE_CLOSE { get; set; }
        public DateTime? MinDate { get; set; }
        public DateTime? MaxDate { get; set; }
        public decimal? SNach { get; set; }
        public decimal? SItog { get; set; }
        public decimal? InVal { get; set; }
        public decimal? OutVal { get; set; }
        public decimal? OutVal_PIF { get; set; }
        public decimal? OutVal_DU { get; set; }
        public decimal? Dividends { get; set; }
        public decimal? Coupons { get; set; }
        public decimal? Income { get; set; }
        public decimal? WAmounr { get; set; }
        public decimal? Res { get; set; }
    }
}
