// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsProcatt.ModelDB
{
    public partial class DivNCouponsDetailsResult
    {
        public int ContractId { get; set; }
        public string ContractName { get; set; }
        public string PaymentType { get; set; }
        public string ShareName { get; set; }
        public DateTime Date { get; set; }
        public decimal? INPUT_VALUE { get; set; }
        public string Valuta { get; set; }
    }
}
