// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsProcatt.ModelDB
{
    public partial class DuOperationHistoryResult
    {
        public long Id { get; set; }
        public bool? IsArchive { get; set; }
        public DateTime Date { get; set; }
        public string OperName { get; set; }
        public string ISIN { get; set; }
        public string ToolName { get; set; }
        public decimal? Price { get; set; }
        public decimal? PaperAmount { get; set; }
        public string RowValuta { get; set; }
        public decimal? RowCost { get; set; }
        public decimal? Fee { get; set; }
        public string Status { get; set; }
    }
}
