// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsProcatt.ModelDB
{
    public partial class DuPositionGrouByElementResult
    {
        public int? VALUE_ID { get; set; }
        public string CategoryName { get; set; }
        public long? InvestmentId { get; set; }
        public long? TypeId { get; set; }
        public string ChildName { get; set; }
        public long? ValutaId { get; set; }
        public string Valuta { get; set; }
        public decimal? Price { get; set; }
        public decimal? Ammount { get; set; }
        public decimal? FinRes { get; set; }
        public decimal? FinResPrcnt { get; set; }
    }
}
