// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsProcatt.ModelDB
{
    public partial class FundOperationHistoryResult
    {
        public int W_ID { get; set; }
        public string W_Date { get; set; }
        public string Order_NUM { get; set; }
        public int WALK { get; set; }
        public short TYPE { get; set; }
        public decimal? RATE_RUR { get; set; }
        public decimal? Amount { get; set; }
        public decimal? VALUE_RUR { get; set; }
        public decimal? Fee_RUR { get; set; }
        public string OperName { get; set; }
        public string Valuta { get; set; }
        public bool? IsArchive { get; set; }
    }
}
