// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportsProcatt.ModelDB
{
    public partial class VDividendsAndCouponsHistory
    {
        public int InvestorId { get; set; }
        public int ContractId { get; set; }
        public int Wiring { get; set; }
        public short Type { get; set; }
        public DateTime PaymentDateTime { get; set; }
        public int Type1 { get; set; }
        public int CurrencyId { get; set; }
        public decimal? AmountPayments { get; set; }
        public string ShareName { get; set; }
        public decimal? Usdrate { get; set; }
        public decimal? Eurorate { get; set; }
        public decimal? AmountPaymentsRur { get; set; }
        public decimal? AmountPaymentsUsd { get; set; }
        public decimal? AmountPaymentsEuro { get; set; }
        public bool? IsArchive { get; set; }
    }
}