// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportsProcatt.ModelDB
{
    public partial class VFundHistory
    {
        public int Investor { get; set; }
        public int FundId { get; set; }
        public int WId { get; set; }
        public DateTime WDate { get; set; }
        public string OrderNum { get; set; }
        public int Walk { get; set; }
        public short Type { get; set; }
        public decimal? RateRur { get; set; }
        public decimal? Amount { get; set; }
        public decimal? ValueRur { get; set; }
        public decimal? FeeRur { get; set; }
        public bool? IsArchive { get; set; }
    }
}