// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportsProcatt.ModelDB
{
    public partial class VInvestorFundDate
    {
        public int Investor { get; set; }
        public int FundId { get; set; }
        public DateTime Date { get; set; }
        public decimal AmountDay { get; set; }
        public decimal? SumAmount { get; set; }
        public decimal? Rate { get; set; }
        public decimal? Usdrate { get; set; }
        public decimal? Evrorate { get; set; }
        public decimal? ValueRur { get; set; }
        public decimal? ValueUsd { get; set; }
        public decimal? ValueEvro { get; set; }
        public decimal? AmountDayPlus { get; set; }
        public decimal? AmountDayPlusRur { get; set; }
        public decimal? AmountDayPlusUsd { get; set; }
        public decimal? AmountDayPlusEvro { get; set; }
        public decimal? AmountDayMinus { get; set; }
        public decimal? AmountDayMinusRur { get; set; }
        public decimal? AmountDayMinusUsd { get; set; }
        public decimal? AmountDayMinusEvro { get; set; }
        public string LsNum { get; set; }
        public bool? IsArchive { get; set; }
    }
}