// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportsProcatt.ModelDB
{
    public partial class VOperationsHistoryContracts
    {
        public long Id { get; set; }
        public int InvestorId { get; set; }
        public int ContractId { get; set; }
        public DateTime Date { get; set; }
        public int? Type { get; set; }
        public string TName { get; set; }
        public string Isin { get; set; }
        public string Investment { get; set; }
        public decimal? Price { get; set; }
        public decimal? Amount { get; set; }
        public decimal? ValueNom { get; set; }
        public int? Currency { get; set; }
        public decimal? Fee { get; set; }
        public int? PaperId { get; set; }
        public bool? IsArchive { get; set; }
    }
}