// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportsProcatt.ModelDB
{
    public partial class VPortFolioDaily
    {
        public int InvestorId { get; set; }
        public int ContractId { get; set; }
        public DateTime PortfolioDate { get; set; }
        public long Id { get; set; }
        public long? InvestmentId { get; set; }
        public int? ValueId { get; set; }
        public int? BalAcc { get; set; }
        public int? Class { get; set; }
        public decimal? Amount { get; set; }
        public decimal? SBalSummaRur { get; set; }
        public decimal? Nominal { get; set; }
        public decimal? RurPrice { get; set; }
        public decimal? NomPrice { get; set; }
        public decimal? ValueRur { get; set; }
        public decimal? ValueNom { get; set; }
        public int? CurId { get; set; }
        public string CurName { get; set; }
        public decimal? Rate { get; set; }
        public DateTime? RateDate { get; set; }
        public decimal? BalSumma { get; set; }
        public DateTime? RecordDate { get; set; }
        public bool? IsArchive { get; set; }
    }
}