// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportsProcatt.ModelDB
{
    public partial class VPositionKeeping
    {
        public int InvestorId { get; set; }
        public int ContractId { get; set; }
        public int ShareId { get; set; }
        public DateTime FifoDate { get; set; }
        public long Id { get; set; }
        public string Isin { get; set; }
        public int? Class { get; set; }
        public long InstrumentId { get; set; }
        public int? CurId { get; set; }
        public DateTime? ObligDateEnd { get; set; }
        public DateTime? OfertaDate { get; set; }
        public string OfertaType { get; set; }
        public bool? IsActive { get; set; }
        public int? InWir { get; set; }
        public DateTime? InDate { get; set; }
        public long? IcNameId { get; set; }
        public int? IlNum { get; set; }
        public int? InDol { get; set; }
        public string IrTrans { get; set; }
        public decimal? Amount { get; set; }
        public decimal? InSumma { get; set; }
        public decimal? InEq { get; set; }
        public decimal? InComm { get; set; }
        public decimal? InPrice { get; set; }
        public decimal? InPriceEq { get; set; }
        public decimal? InPriceUkd { get; set; }
        public decimal? TodayPrice { get; set; }
        public decimal? ValueNom { get; set; }
        public decimal? Dividends { get; set; }
        public decimal? Ukd { get; set; }
        public decimal? Nkd { get; set; }
        public decimal? Amortizations { get; set; }
        public decimal? Coupons { get; set; }
        public int? OutWir { get; set; }
        public DateTime? OutDate { get; set; }
        public int? OdId { get; set; }
        public long? OcNameId { get; set; }
        public int? OlNum { get; set; }
        public int? OutDol { get; set; }
        public decimal? OutPrice { get; set; }
        public decimal? OutSumma { get; set; }
        public decimal? OutEq { get; set; }
        public DateTime? RecordDate { get; set; }
        public bool? IsArchive { get; set; }
    }
}